server:
  port: ${PORT:8080}

spring:
  application:
    name: tttnBE

  datasource:
    url: jdbc:sqlserver://ticketxDB.mssql.somee.com:1433;databaseName=ticketxDB;encrypt=true;trustServerCertificate=true;
    username: courage123_SQLLogin_1
    password: ctgnf2bcvj
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

# ==========================================
# CẤU HÌNH WEB3 (BLOCKCHAIN)
# ==========================================
web3:
  rpc:
    # Đây là đường dẫn kết nối vào mạng thử nghiệm của Binance (BSC Testnet)
    url: https://ethereum-sepolia-rpc.publicnode.com
  admin:
    # Lát nữa bạn tạo ví xong thì copy cái địa chỉ 0x... dán vào đây
    wallet: "0xfF7154E5D44951a824E4Be4909f588d553f98383"
    private-key: "e4a56eaf6ebce9183ac7ac7e7de6a51e03bba565f9260be458d60359f868fb09"
  contract:
    address: "0x37163CfCF134747aC0C84842A40Da18E46B59fDb"